#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pageCount' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER p
#

def pageCount(n, p):
    if n%2==0: 
        even =True
    else: 
        even = False
        

    if even:
        if n ==p:
            return 0
        if (n-p)//2 == 0:
            chosen = 1
        else: 
            chosen = (n-p)//2
        return(min(p//2,chosen))
    else:
        
        return(min(p//2,(n-p)//2))
          
            
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    p = int(input().strip())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
