#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    minSum = 0 
    maxSum = 0 
    
    min = sorted(arr)
    for x in range(0,4):
        minSum = minSum + min[x]
    
    
    max = list(reversed(min))
    for x in range(0,4):
        maxSum = maxSum + max[x]
        
        
    print(minSum,maxSum)
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
