#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    arr = sorted(a)

    count = 0 
    maxCount = 0
    for x in range(0,len(arr)):
        y= x
        while abs(arr[x]-arr[y]) <=1 and y<len(arr)-1:
            count += 1
            y +=1
            if y == len(arr)-2 and abs(arr[x]-arr[y+1]) <=1:
                count +=1
        
        if count > maxCount:
            maxCount = count
        count = 0 
    return maxCount
        
    
    print(subArr)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
